#!/bin/sh
audioctl speakers

~/.fehbg

st -t jabber.ccc.de -c chat -g 125x55+32+22 -e jackline -f .config/xmpp/jabber.ccc.de&
st -t jabber.otr.im -c chat -g 125x35+32+857 -e jackline -f .config/xmpp/jabber.otr.im&
st -t irssi -c chat -g 228x68+936+22 -e irssi&
st -t top -c monitor -g +1994+1074 -e top -P -s 5&

batterymonitor&

exec cwm
