#!/bin/sh

AUDEV="$(sysctl -n hw.snd.default_unit)"

case $AUDEV in
  1)
    mixer -s vol 75 pcm 75 > /dev/null
    ;;
  3)
    mixer -s vol 20 pcm 20 > /dev/null
    ;;
  *)
    mixer -s vol 50 pcm 50 > /dev/null
esac
